// <auto-generated />
using System;
using Gdc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gdc.Data.Migrations
{
    [DbContext(typeof(CourDbContext))]
    [Migration("20221224115832_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gdc.Domain.Modeles.CoursGenerique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDerniereModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoursGeneriques");
                });

            modelBuilder.Entity("Gdc.Domain.Modeles.Enseignant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDerniereModification")
                        .HasColumnType("datetime2");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NumeroExterne")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Specialite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("Gdc.Domain.Modeles.Matiere", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeMatiere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CoursGeneriqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDerniereModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EnseignantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NbreHeureInitiale")
                        .HasColumnType("int");

                    b.Property<Guid>("NiveauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("NoteDeValidation")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CoursGeneriqueId");

                    b.HasIndex("EnseignantId");

                    b.HasIndex("NiveauId");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("Gdc.Domain.Modeles.Niveau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDerniereModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationCycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationFiliere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NumeroExterne")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ValeurCycle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("Gdc.Domain.Modeles.Matiere", b =>
                {
                    b.HasOne("Gdc.Domain.Modeles.CoursGenerique", "CoursGenerique")
                        .WithMany("Matieres")
                        .HasForeignKey("CoursGeneriqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gdc.Domain.Modeles.Enseignant", "Enseignant")
                        .WithMany("Matieres")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gdc.Domain.Modeles.Niveau", "Niveau")
                        .WithMany("Matieres")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursGenerique");

                    b.Navigation("Enseignant");

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("Gdc.Domain.Modeles.CoursGenerique", b =>
                {
                    b.Navigation("Matieres");
                });

            modelBuilder.Entity("Gdc.Domain.Modeles.Enseignant", b =>
                {
                    b.Navigation("Matieres");
                });

            modelBuilder.Entity("Gdc.Domain.Modeles.Niveau", b =>
                {
                    b.Navigation("Matieres");
                });
#pragma warning restore 612, 618
        }
    }
}
